### ISSUE TITLE
Should be able to create an app

### ISSUE THREAD

**Issue by GantMan** [GantMan/irrigate#2]
Time for irrigate to create an app based off of the latest from https://github.com/infinitered/react_native_base

**Comment by skellock** [comment]
![image](https://cloud.githubusercontent.com/assets/68273/14179054/7ad1faf4-f72b-11e5-814f-94665e3bdfec.png)

![image](https://cloud.githubusercontent.com/assets/68273/14179110/b8c72fbe-f72b-11e5-9d89-050edca70900.png)

YOU DID IT @GantMan !!!!!
